In [4]:
import numpy as np
import pandas as pd

from pylife.stress.histogram import *
import pylife.stress.timesignal as ts
from pylife.stress.rainflow import *
import pylife.stress.equistress

import pylife.strength.meanstress
from pylife.strength import miner
from pylife.strength import sn_curve
from pylife.strength.miner import MinerElementar, MinerHaibach
from pylife.strength import failure_probability as fp

from pylife.materialdata.woehler.diagrams.woehler_curve_diagrams import WoehlerCurveDiagrams

import pylife.mesh.meshplot
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
import matplotlib as mpl

from scipy.stats import norm

from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets
import io
from IPython.display import HTML
import base64

# mpl.style.use('seaborn')
# mpl.style.use('seaborn-notebook')
mpl.style.use('bmh')
%matplotlib inline

In [21]:
filename = 'Data.xlsx'

stress = pd.read_excel(filename)
stress

,Node_id,Elem_id,X,Y,Z,S11,S22,S33,S12,S23,S13
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,307.0,0.0,0.0,0.0,-1.466051,-0.483797,0.0,-0.305723,0.0,0.0
2,2.0,283.0,10000000.0,0.0,0.0,-1.000225,-0.000099,0.0,-0.003099,0.0,0.0
3,3.0,306.0,400000.0,0.0,0.0,-1.202002,-0.037334,0.0,-0.102140,0.0,0.0
4,4.0,305.0,800000.0,0.0,0.0,-1.068910,-0.015131,0.0,-0.008736,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
348,348.0,21.0,7583445.0,2298922.0,0.0,-0.712128,-0.074158,0.0,-0.048824,0.0,0.0
349,349.0,18.0,7134942.0,2647036.0,0.0,-0.533661,-0.023067,0.0,0.053327,0.0,0.0
350,350.0,23.0,2870689.0,2661075.0,0.0,-0.589137,-0.056850,0.0,-0.037476,0.0,0.0
351,351.0,24.0,2418450.0,2667289.0,0.0,-0.689960,-0.099814,0.0,-0.037664,0.0,0.0
352,352.0,17.0,7159829.0,2270538.0,0.0,-0.603484,-0.037706,0.0,-0.076353,0.0,0.0

In [24]:

""" Equivalent stress """

s_vm = stress.groupby('Elem_id').mean().equistress.mises().rename(columns={'mises': 'sigma_a'})
s_vm = 2*s_vm/s_vm.max()
display(s_vm)

          sigma_a
Elem_id
1.0      0.471123
2.0      0.726292
3.0      0.714047
4.0      0.796608
5.0      0.620596
...           ...
303.0    0.685309
304.0    0.648086
305.0    0.637707
306.0    0.719041
307.0    0.839856

[297 rows x 1 columns]

In [25]:

""" Scale with """
ampl_fe = pd.DataFrame(data = amplitude, columns = ["ampl"] ,index =cycles)
display(ampl_fe)

NameError: name 'amplitude' is not defined